### ISSUE TITLE
抽奖大转盘

### ISSUE THREAD

**Issue by chenyucheng0503** [monk-coder/dust#1]
![image](https://user-images.githubusercontent.com/42239907/112840961-85f6ad80-90d2-11eb-80ad-2bded56e2b23.png)
遇到这种奖品，要怎么判断是哪家店铺，是否会自动填写收货地址呢

**Comment by monk-coder** [comment]
@chenyucheng0503 1、判断店铺看通知
2、不会自动填写收货地址
3、是否需要购物才可领取奖品请咨询卖家
4、获奖1小时没有处理会失去获奖资格。

**Comment by chenyucheng0503** [comment]
> @chenyucheng0503 1、判断店铺看通知
> 2、不会自动填写收货地址
> 3、是否需要购物才可领取奖品请咨询卖家
> 4、获奖1小时没有处理会失去获奖资格。

感谢

**Comment by qxy0789** [comment]
这个电饭煲是个优惠券，券后699元
