### ISSUE TITLE
探秘无限星空 出现错误

### ISSUE THREAD

**Issue by Mirasc** [monk-coder/dust#18]
昨天跑正常，今天就这样了， 感谢开发者
TypeError: Cannot read property 'itemId' of null

**Comment by monk-coder** [comment]
> 昨天跑正常，今天就这样了， 感谢开发者
> 
> TypeError: Cannot read property 'itemId' of null

完整的日志

**Comment by happy-happ** [comment]
> > 昨天跑正常，今天就这样了， 感谢开发者
> > TypeError: Cannot read property 'itemId' of null
> 
> 完整的日志



> > 昨天跑正常，今天就这样了， 感谢开发者
> > TypeError: Cannot read property 'itemId' of null
> 
> 完整的日志
![image](https://user-images.githubusercontent.com/72593907/117784527-3fba6f80-b276-11eb-8d3b-b2f919aacc98.png)
老大，活动任务没做完，就出现这个

**Comment by adolfunderwood** [comment]
> 刚想说，修复之后，多个账号切换不了了😂
> 
> 一直卡在第一个账号，然后就看到作者说死循环
> 一直输出这段
> 
> ```
> May 11 20:25:18 不执行 - 开通品牌会员 
> May 11 20:25:18 不执行 - 邀请好友助力 
> May 11 20:25:18 已经完成所有 关注并浏览大牌店铺
> May 11 20:25:18 已经完成所有 逛精选会场
> May 11 20:25:18 已经完成所有 关注并浏览精选频道
> May 11 20:25:18 已经完成所有 商品加入购物车
> ```

已经修好了，更新一下就好了。抱歉，造成不便。

**Comment by VergLsm** [comment]
> > 刚想说，修复之后，多个账号切换不了了😂
> > 一直卡在第一个账号，然后就看到作者说死循环
> > 一直输出这段
> > ```
> > May 11 20:25:18 不执行 - 开通品牌会员 
> > May 11 20:25:18 不执行 - 邀请好友助力 
> > May 11 20:25:18 已经完成所有 关注并浏览大牌店铺
> > May 11 20:25:18 已经完成所有 逛精选会场
> > May 11 20:25:18 已经完成所有 关注并浏览精选频道
> > May 11 20:25:18 已经完成所有 商品加入购物车
> > ```
> 
> 已经修好了，更新一下就好了。抱歉，造成不便。

赞！
